name: Test Project
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: FirstStep
              run: echo "Test"
            - name:  download code
              uses: actions/checkout@v3
            - name: Install node
              uses: actions/setup-node@v3
              with:
               node-version: 18

