name: Test Project
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: FirstStep
              run: echo "Test"
            - name:  download code
              uses: actions/checkout
            - name: Install node
              uses: actions/setup-node
              with:
               node-version: 18
            - name: install dependency
              run: npm ci
            - name: RUn etsts
              run: npm run test  
    deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: FirstStep
          run: echo "Test"
        - name:  download code
          uses: actions/checkout@v3
        - name: Install node
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: install dependency
          run: npm ci
        - name: RUn etsts
          run: npm run build
          

